### ISSUE TITLE
Kann nicht mit octopi verbinden

### ISSUE THREAD

**Issue by eagleye2** [klein0r/ioBroker.octoprint#1]
Zuerst einmal danke für den Adapter
Ich kann mich leider nicht mit octopi verbinden. Habe die richtige API eingetragen. Trotzdem bleibt das Licht Gelb. Kann es sein dass es mit den Access Control zusammenhängt?
Habe ein Username und Passwort, dass ich nirgends eintragen kann.
Danke vorab.

**Comment by RoboCop0815** [comment]
Moin Moin,
habe das gleiche Problem... Anzeige bleibt gelb...
habe auch User und PW 
Grüße Robbie

**Comment by ZeroCool80** [comment]
Servus,
habe auch keine Verbindung!

Gruß

**Comment by mrMuppet** [comment]
bei mir leider auch.

**Comment by Moormerlander** [comment]
Wird dieser Adapter nicht mehr gepflegt?

**Comment by kxn25** [comment]
Sieht nicht aus als würde weiter daran gearbeitet!
Also ich komm auf den Printer mit Port 80.
Aber mein Iobroker kriegt immer LOG mit der Meldung null, das nerft...

**Comment by Camel2k** [comment]
Gibt es eine Lösung mittlerweile?

**Comment by Moormerlander** [comment]
Offensichtlich pflegt das niemand mehr. Ich habe es über FHEM gelöst, da ich meinen verbliebenen Homematic-Kram noch damit betreibe und nicht extra ne CCU für das bisschen aufsetzen will.  So mache ich das auch mit Octoprint. Über den FHEM-Adapter funzt Octoprint super und ich kann alle möglichen Stati (Readings) abfragen und in meine Scripts einbauen.

**Comment by klein0r** [comment]
Der Adapter wurde in den letzten Versionen komplett überarbeitet.
Sollte alles behoben sein 👍

**Comment by npeter** [comment]
Verbindung mit API nicht erfolgreich:
Log...
octoprint.0 | 2020-11-26 01:19:10.148 | info | (29431) OctoPrint API not connected
octoprint.0 | 2020-11-26 01:19:10.147 | info | (29431) getaddrinfo ENOTFOUND http
octoprint.0 | 2020-11-26 01:19:10.106 | info | (29431) starting. Version 1.0.1 in /opt/iobroker/node_modules/iobroker.octoprint, node: v12.18.4, js-controller: 3.1.6

Hätte eigentlich erwartet Account-Daten konfigurieren zu müssen.
Hat jemand eine Idee?

**Comment by npeter** [comment]
Problem gelöst. Hatte URL statt IP konfiguriert. Adapter funktioniert!
Danke für den Adapter!!!

**Comment by klein0r** [comment]
@npeter Sehr gut!

*Für die Zukunft aber bitte einen neuen Issue öffnen, und nicht an einen geschlossenen anhängen, welcher über ein Jahr alt ist.*
