### ISSUE TITLE
Please add you adapter to our repository

### ISSUE THREAD

**Issue by ioBrokerChecker** [klein0r/ioBroker.octoprint#12]
We saw your adapter and if it is ready please request that it is added to the repository. With this it becomes available for all users. Please consult https://github.com/ioBroker/ioBroker.repositories#add-a-new-adapter-to-the-latest-repository and the following sections for more details.
If you need help, contact us in the forum https://forum.iobroker.net/ or in the developer chat https://github.com/iobroker-community-adapters/info .

Thank you for your support.

**Comment by Mr-Markus** [comment]
@klein0r 
Kannst du bitte den Adapter hinzufügen dass er auch ohne Katze im ioBroker zu installieren ist?

Würde gerne ein Skript damit bauen, welches den Drucker bei Überhitzung abschaltet.

Danke

**Comment by klein0r** [comment]
Der Adapter ist bereits im Latest-Repository verfügbar. Für Stable muss ich noch etwas testen und die letzten kleinen Fehler fixen. Also bitte nicht über die OctoCat installieren, sondern einfach aus dem latest-Repository ziehen.
