### ISSUE TITLE
DP für Terminal Steuerung

### ISSUE THREAD

**Issue by mczeus** [klein0r/ioBroker.octoprint#14]
Ist es auch möglich einen Datenpunkt zu erstellen in dem ich ein gcode befehl senden kann.
Wie z.b direkt auf dem WebUi kartei Terminal "G1 Z20" damit die Düse hochfährt?
Also Steuerung der XYZ Achsen.

**Comment by klein0r** [comment]
Ist in Version 0.0.5 enthalten
