### ISSUE TITLE
Send „Printer Command“ not working

### ISSUE THREAD

**Issue by rnc11** [klein0r/ioBroker.octoprint#18]
It seems that the possibility to send commands to OctoPrint is not working. 

I've tried several M or G commands without any effect.

Unfortunately there is no documentation how the commands need to formatted. But I would expect that an Value of "G28" in octoprint.0\command\printer should trigger the command.
I always get an "(23147) printer command not allowed: G28" back in the log.

**Versions:**  
 - Adapter version: 0.0.2
 - JS-Controller version: 3.1.6
 - Node version: v10.22.0
 - Operating system: linux (Raspberry PI 4)

**Comment by klein0r** [comment]
You mean ".command.custom"? This is documented here: https://docs.octoprint.org/en/master/api/printer.html#send-an-arbitrary-command-to-the-printer

**Comment by rnc11** [comment]
Hi,

 

I mean the “format” of the value that is needed here:



 

I have tried several values (with []{} “”…) but all without any effect.

I always get an error back in the ioBroker log: (13593) printer command not allowed: xyz

 

Could you please provide one running example of an G or M command that works (using the great ioBroker.octoprint adapter)?

 

regards

**Comment by klein0r** [comment]
Just tested `G28` and everything worked perfectly.

![Screenshot 2020-10-29 at 19 43 11](https://user-images.githubusercontent.com/1959049/97618208-0da29800-1a1f-11eb-8d53-8b66ae8f450c.png)

Please provide more information about the tested command and the issue. I think you are using the wrong field for the command (as already mentioned in the last comment...).
