### ISSUE TITLE
octoprint.0.printjob.progress.completion wrong

### ISSUE THREAD

**Issue by p3pp0** [klein0r/ioBroker.octoprint#19]
Hey Matthias,

leider ist die Prozentzahl unter octoprint.0.printjob.progress.completion seit dem letzten Octoprint-Update dauerhaft falsch... :-(

Wenn du das fixen könntest wäre genial, danke dir!

**Comment by klein0r** [comment]
Kannst Du genauer definieren, was "falsch" bedeutet? Ungenau? Oder immer 0?

**Comment by p3pp0** [comment]
Bitte entschuldige, das war keine gute Angabe von mir...

Der Prozentwert ist immer ganz deutlich zu niedrig bzw. entspricht nicht dem Prozentwert aus der Octoprint GUI. So, als hätte er teils mehrere Stunden "Delay".

Es liegt aber definitiv nicht am Refresh-Intervall - der Wert wird regelmäßig aktualisiert..

Bitte lass mich wissen wenn ich noch irgendwie weiterhelfen kann

**Comment by klein0r** [comment]
In welcher Version hattest Du das Verhalten denn? In 0.0.6 ist bei mir alles korrekt berechnet.

**Comment by Leviathan09** [comment]
Ich habe das Problem auch, benutze die Version 0.0.6
Habe dir mal einen Screenshot angehängt. Octoprint GUI 23%, bei den Datenpunkten des Adapters 17%
![vergleich_octoprint_adapter](https://user-images.githubusercontent.com/39566011/97716871-709a3a80-1ac4-11eb-83f4-0db4623d5940.JPG)

**Comment by p3pp0** [comment]
@klein0r bei mir exakt genauso wie bei @Leviathan09 
Lass mich gerne wissen wenn ich noch irgendwelche Infos liefern kann

**Comment by klein0r** [comment]
Habt ihr noch irgendwelche Plugins installiert, welche den Fortschritt und Restzeit genauer berechnen? Über die API wird als Fortschritt einfach nur die aktuelle Position in der gcode-Datei vs Gesamtgröße gerechnet.

**Comment by Ilovegym66** [comment]
Hi, bei mir stimmt die Anzeige vom Adapter mit dem von Octoprint überein. Ich habe keine weiteren Plugins disbezüglich installiert. 
Vielleicht aktualisiert bei euch der Browser nicht schnell genug?

**Comment by Leviathan09** [comment]
Ich habe ein Plugin installiert was mir die Zeit genauer berechnet
Aber weiß nicht ob das die Prozentangabe beeinflusst

**Comment by klein0r** [comment]
@Leviathan09 Aber klar, darum geht es ja. Ohne die Plugins dauern z.B. die ersten Prozente super lange, weil z.B. eine Bodenplatte gedruckt wird. Da dauert es Stunden bis das erste Prozent fertig ist (was ja mathematisch keinen Sinn ergibt). Solche Plugins optimieren das dann. Ich mach hier zu.

**Comment by p3pp0** [comment]
@klein0r : die Ursache ist (bei mir) das Plugin Print-Time-Genius.. deaktiviert man dieses, stimmen die Prozente wieder überein.
Die errechnete Endzeit ist halt dann wieder quatsch - die durch das Plugin-Verbesserte Endzeit wurde in iobroker auch wieder richtig angezeigt :-)

**Comment by klein0r** [comment]
@p3pp0 Ich muss mal schauen, ob das Plugin auch die Daten per API ausgibt. Falls das Fall ist, kann ich stattdessen die Daten nehmen

**Comment by p3pp0** [comment]
@klein0r das wäre klasse! Ohne Plugin sind nämlich die Prozent-Zahlen und auch die berechnete Endzeit völlige Grütze... mit Plugin  stimmt zumindest Rest/Endzeit ;-) Komisch, dass das Problem erst nach einem Update aufgetaucht ist..

**Comment by klein0r** [comment]
@p3pp0 Mh, ich nehme nach wie vor die gleichen Zahlen aus der API. Ich kann nur nehmen, was ich bekomme.

**Comment by p3pp0** [comment]
@klein0r  @Leviathan09 
Meine Lösung:

![image](https://user-images.githubusercontent.com/9203649/99199649-ef6bc480-27a0-11eb-8579-fa6c0addd1d6.png)
