### ISSUE TITLE
Not really an issue - is „finishing“ gone?

### ISSUE THREAD

**Issue by beef76** [klein0r/ioBroker.octoprint#25]
Just wonder if with latest octoprint update the printer status "finishing" is gone?
Had a little script turning my led frame into different color mode close before print is really finished. Not working anymore 😞

**Comment by klein0r** [comment]
I don't know. Just showing the printer state which is provided by the api

**Comment by beef76** [comment]
Wasn't able to find anything about changes here in the 1.50/1.51 version 😏 but not that important. Can live without "finishing" status and therefore close this one 👍🏻

**Comment by klein0r** [comment]
Feel free to open an issue in the OctoPrint project on GitHub :)

**Comment by beef76** [comment]
not that important, Matthias :-) thanks!
