### ISSUE TITLE
inkompatibel mit dem "UI Customizer Plugin"

### ISSUE THREAD

**Issue by zion2k** [klein0r/ioBroker.octoprint#32]
Hallo,
ich nutze das [UI Customizer Plugin](https://github.com/LazeMSS/OctoPrint-UICustomizer) und leider lässt sich damit der Adapter nicht mit OctoPrint verbinden.

Im Log findet man folgen Fehler:
2021-01-07 22:13:54.797 - error: octoprint.0 (7558) Cannot read property 'toFixed' of null

UI Customizer 0.1.2.3
OctoPrint 1.5.2
Python 2.7.13
OctoPi 0.16.0

**Update:** Ich habe nun mal das UI Customizer Plugin deaktiviert, so ließ sich der OctoPrint Adapter verbinden. Danach habe ich das Plugin wieder aktiviert und der Adapter hat sich, entgegen meiner Erwartung, wieder verbunden. Im Log finde ich nun auch keine Fehler mehr.
Es scheint als ob er den Fehler nur bei aktiviertem Plugin und erstmaligen Verbindungsaufbau auftritt. Wenn die Verbindung bereits einmal erfolgreich hergestellt wurde, scheint das Plugin kein Problem mehr zu sein.

**Comment by klein0r** [comment]
Das kann eigentlich nicht an dem Plugin liegen - der Fehler ist bei mir auch schon einmal aufgetreten, aber ich konnte ihn danach nicht reproduzieren.
