### ISSUE TITLE
Systemcommands: core shutdown für herunterfahren, gibt es auch eine möglichkeit für core start?

### ISSUE THREAD

**Issue by AndiSch87** [klein0r/ioBroker.octoprint#35]
Hallo Matthias,
super Arbeit. Ich finde die neuen Möglichkeiten, die man mit dem Adapter erhält, einfach super.
Ich Möchte nachdem mein 3D druck fertig ist, den Drucker über einen Sonoff ausschalten.
Danach will ich den Raspberry herunterfahren, dies kann ich ja mit core/shutdown umsetzen.
Wie bekomme ich es hin den Raspberry dann wieder zu starten, bis jetzt habe ich nur die Möglichkeit ihn kurzzeitig vom Strom zu trennen, damit er bootet.

**Comment by klein0r** [comment]
Naja das wird technisch schwierig :) Du kannst ja schlecht Befehle an ein nicht laufendes System senden.
Also hilft nur ein Zwischenstecker o.ä. um das Netzteil auszuschalten wenn er fertig runter gefahren ist und dann eben diesen Zwischenstecker zu nutzen um den Raspberry Pi wieder booten zu lassen.
