### ISSUE TITLE
GPIO auslesen 

### ISSUE THREAD

**Issue by fulwerin** [klein0r/ioBroker.octoprint#37]
Guten Tag

Könnte man irgendwie die GPIO Pins vom Octopi Server auf dem ioBroker Server auslesen?
Wenn das nicht geht könnte man das im Adapter hinzufügen?

vielen Dank

**Comment by klein0r** [comment]
Der Adapter bedient nur die offizielle API von OctoPrint. Da gibt es keine Möglichkeit die GPIO Pins auszulesen.
Außer es gibt ein Plugin für OctoPrint, welches die API erweitert.

**Comment by mczeus** [comment]
Hätte gerne etwas ähnliches!
Habe das OctoPrint-Enclosure Plugin am laufen mit dem ich Lüfter und Beleuchtung steuern kann. Es gibt dafür auch eine API, ist es möglich das in den Adapter zu integrieren?
https://github.com/vitormhenrique/OctoPrint-Enclosure/wiki/API-Control
