### ISSUE TITLE
Fehler bei ausgeschaltetem Octoprint

### ISSUE THREAD

**Issue by bauer1418** [klein0r/ioBroker.octoprint#4]
Hi Leute,

mir ist aufgefallen dass das Plugin bei ausgeschaltem Pi trotzdem meldet dass es mit Octoprint verbunden ist. Hat jemand anderes auch dieses Problem?

MFG Andreas

**Comment by Ilovegym66** [comment]
ja, hier auch. Keine serielle Verbindung zum Drucker und er meckert fleissig das log voll...

**Comment by Ilovegym66** [comment]
siehe Issue#2
das gleiche mit Fehlermeldungen.

**Comment by reloxx13** [comment]
auch werden die werte nicht resetten, temps bleiben bei der letzten ausgelesenen.

**Comment by sonntam** [comment]
> siehe Issue#2
> das gleiche mit Fehlermeldungen.
> aber hier ein Fork, indem das abgeschaltet ist
> https://github.com/resper/ioBroker.octoprint

Hast Du schon probiert einen PR zu submitten?
