### ISSUE TITLE
Add GCode Viewer

### ISSUE THREAD

**Issue by TJJochen** [klein0r/ioBroker.octoprint#40]
Please add the GCode Viewer to show on ioBroker VIS

Thx :-) 

![image](https://user-images.githubusercontent.com/35068587/111003331-3486b880-8387-11eb-9158-4bc697a04430.png)

**Comment by klein0r** [comment]
Please tell me how to get those information over the API 😄

**Comment by TJJochen** [comment]
Oh, i don't know, that this information not supported by the API. Sorry
