### ISSUE TITLE
octoprint.1 als 2te octoprint Instanz geht im ioBroker nicht

### ISSUE THREAD

**Issue by dg1bor** [klein0r/ioBroker.octoprint#44]
Hallo Matthias,

meine erste octoprint.0 Instance mit einem Creality Ender 3Plus funktioniert ohne Probleme,
jedoch wollte ich eine zweite Instance octoprint.1 für einen Prusa MK3S dazu packen.
Die API wird jedoch nicht erkannt.

Beim Ender3 (Merlin Firmware) läuft ein Raspi mit OctoPrint 1.6.0 
Beim Prusa (Prusa Firmware) läuft ein Raspi mit OctoPrint 1.6.0

Deine  octoprint wird immer aktuell gehalten.

Die API wurde von Octoprint direkt in die Instanz kopiert, eine Verbindung wird aber nicht hergestellt. gelber Punkt
API neu erzeugt und kopiert, geht auch nicht 3 mal versucht.
In der ioBroker Instanz sind bei beiden bis auf die IP und API die gleichen Werte enthalten.

wo kann der Fehler liegen

Gruß
Gerhard Bauer

![Bildschirmfoto vom 2021-05-03 10-30-33](https://user-images.githubusercontent.com/19173567/116856039-b31b0c00-abfa-11eb-8351-0dd322f14898.png)

**Comment by klein0r** [comment]
Ich habe auch Probleme seit dem Update auf 1.6.0 gestern. Muss ich mir angucken

**Comment by klein0r** [comment]
Bitte mit 1.1.0 testen
