### ISSUE TITLE
Keine Instanz

### ISSUE THREAD

**Issue by amnesia106** [klein0r/ioBroker.octoprint#5]
Nach installieren über die "katze" wird keine Instanz in iobroker angezeigt. 
Auch: `iobroker upload octroprint` brachte keinen Erfolg

**Comment by klein0r** [comment]
Du hast aber auf dem Plus-Zeichen schon eine neue Instanz hinzugefügt?
Gerade getestet, klappt einwandfrei

**Comment by Moormerlander** [comment]
Aber leider funktioniert der Adapter nicht. Habe das vor längerer Zeit aufgegeben und machen nun den Umweg über ein FHEM-Modul in Verbindung mit dem FHEM-Adapter von ioBroker, das funktioniert einwandfrei. Ich hatte schon vor längerer Zeit nachgefragt ob dieser Adapter überhaupt noch gepflegt wird, aber darauf leider keine Antwort erhalten.
