### ISSUE TITLE
API Schlüssel verschwindet und Instanz bleibt gelb

### ISSUE THREAD

**Issue by Ceel84** [klein0r/ioBroker.octoprint#51]
In Admin 5.0.27 verschwindet bei mir der API Schlüssel immer, wodurch iobroker immer die Verbindung verliert.

 - Adapter version: 1.1.0
 - JS-Controller version: 3.3.10
 - Node version: 12.22.1
 - Operating system: Proxmox vm

**Comment by klein0r** [comment]
Lass mich raten: Du stoppst und startest den Adapter mit einem Script?

**Comment by Ceel84** [comment]
Hallo
Ja so sollte es laufen.
Habe das Script aber deaktiviert und habe den gleichen Fauler.

**Comment by klein0r** [comment]
Du hast das Script deaktiviert, dann den API-Key hinterlegt und gespeichert?
Wann genau "verschwindet" er dann wieder?

**Comment by Ceel84** [comment]
Ja habe ich.
Kann ich nicht genau sagen.
Irgendwann ist er wieder gelb.

**Comment by Ceel84** [comment]
Warum sollte das Script ein Problem verursachen?

**Comment by klein0r** [comment]
see #45

**Comment by Ceel84** [comment]
Das werde ich Mal testen danke.
Kann sein das es nur daran liegt
Sorry dann

**Comment by klein0r** [comment]
Ich dachte das hast Du gerade ausgeschlossen?!

**Comment by Ceel84** [comment]
Du hast recht!
 Es liegt wirklich am Script.
habe einfach Adaper deaktiviert über den alive dp

danke und sorry nochmal

bin bei dem ganzen hin und her Probieren durcheinander gekommen was ich genau getestet hatte und was nicht!

**Comment by Ceel84** [comment]
Es besteht trotz Deaktivierung des Scripts das die Instanz gelb wird.
Der API Code bleibt aber bestehen.

**Comment by bluefish007** [comment]
Habe leider das selbe Problem! Instanz wird während dem Drucken irgendwann gelb... (seit Admin 5 Version)

**Comment by klein0r** [comment]
duplicate of #50
