### ISSUE TITLE
Invalid character in header content ["X-Api-Key"]Bug report

### ISSUE THREAD

**Issue by jheisel01** [klein0r/ioBroker.octoprint#53]
### The problem

After updating iobroker the adapter doesn't start anymore. 
In the protocol log this messages is logged:
**Invalid character in header content ["X-Api-Key"]**
Adapter version : 1.1.1
iobroker: v5.1.23
NPM: 6.14.14

regards,

Juergen

### Version of ioBroker js-controller

v12.22.4

### Version of Adapter

1.1.1

### Operating system running ioBroker

Debian 10.10

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

Quelle | Zeit | error | Nachricht
-- | -- | -- | --
octoprint.0 | 2021-08-10 21:50:23.941 | error | Invalid character in header content ["X-Api-Key"]
octoprint.0 | 2021-08-10 21:50:13.940 | error | Invalid character in header content ["X-Api-Key"]
octoprint.0 | 2021-08-10 21:50:03.937 | error | Invalid character in header content ["X-Api-Key"]
octoprint.0 | 2021-08-10 21:49:53.935 | error | Invalid character in header content ["X-Api-Key"]
octoprint.0 | 2021-08-10 21:49:43.937 | error | Invalid character in header content ["X-Api-Key"]
octoprint.0 | 2021-08-10 21:49:33.931 | error | Invalid character in header content ["X-Api-Key"]
octoprint.0 | 2021-08-10 21:49:23.929 | error | Invalid character in header content ["X-Api-Key"]
octoprint.0 | 2021-08-10 21:49:13.928 | error | Invalid character in header content ["X-Api-Key"]
octoprint.0 | 2021-08-10 21:49:03.926 | error | Invalid character in header content ["X-Api-Key"]
octoprint.0 | 2021-08-10 21:48:53.924 | error | Invalid character in header content ["X-Api-Key"]

**Comment by klein0r** [comment]
The API key is stored encrypted since version 1.1.0

Since this is a breaking change, you have to re-enter your API key again in the instance settings.
