### ISSUE TITLE
[Request] Daten aus Plugin DisplayLayerProgress 

### ISSUE THREAD

**Issue by neo862** [klein0r/ioBroker.octoprint#58]
Besteht die Möglichkeit die Daten aus dem Octoprint Plugin (https://github.com/OllisGit/OctoPrint-DisplayLayerProgress) auszulesen und in den IOBroker zu bekommen.

Das würde z.B. Layer oder Höhenabhängige Smarthomebefehle erlauben. (z.B. Im firstLayer Licht 100% anschließend auf 50% dimmen, etc.)

Gruß
Stefan

**Comment by klein0r** [comment]
Kommt in die nächste Version, muss es noch testen

**Comment by joergeli** [comment]
Ich habe die aktuelle Version des Octoprint-Adapters **V 2.0.7** installiert,
habe aber Probleme mit dem DisplayLayerProgress-Plugin.

Ich habe das Problem im ioBroker-Forum unter:
https://forum.iobroker.net/topic/50701/octoprint-2-0-7-problem-mit-display-layer-progress
näher beschrieben (geht für mich dort enfacher, als hier)

**Comment by Negalein** [comment]
gleiches Problem mit 2.0.7 wie @joergeli 

Gesamtlayer passt. Aber der aktuelle Layer wird mit `-1` angezeigt.

![objects - ioBroker (3)](https://user-images.githubusercontent.com/45309436/147448206-052f4f8c-2cd4-4447-8e18-14c0bf606be6.png)
![5  14 25  printing ](https://user-images.githubusercontent.com/45309436/147448209-e3a01d45-60bd-4500-a201-a2cb49c5a5aa.png)

**Comment by klein0r** [comment]
Habe den Fehler schon behoben, Fix kommt in die nächste Version

**Comment by joergeli** [comment]
Danke dafür !

**Comment by klein0r** [comment]
Bitte 2.1.0 testen

**Comment by joergeli** [comment]
Mit V2.1.0 funktioniert die Layer-Anzeige korrekt .
