### ISSUE TITLE
timeout of 2000ms exceededBug report - only 2.0.6

### ISSUE THREAD

**Issue by OberfragGER** [klein0r/ioBroker.octoprint#63]
### The problem

Hi,
ich bekomme aktuell immer timeouts beim verbinden. Habe bereits den Adater neu installiert.

browser.user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
connectivity.connection_check: 1.1.1.1:53
connectivity.connection_ok: True
connectivity.enabled: True
connectivity.online: True
connectivity.resolution_check: octoprint.org
connectivity.resolution_ok: True
env.hardware.cores: 4
env.hardware.freq: 900.0
env.hardware.ram: 915730432
env.os.bits: 32
env.os.id: linux
env.os.platform: linux
env.plugins.pi_support.model: Raspberry Pi 2 Model B Rev 1.1
env.plugins.pi_support.octopi_version: 0.18.0
env.plugins.pi_support.throttle_state: 0x0
env.python.pip: 20.3.3
env.python.version: 3.7.3
env.python.virtualenv: True
octoprint.safe_mode: False
octoprint.version: 1.7.2
systeminfo.generator: zipapi

### Version of nodejs

v14.18.2

### Version of ioBroker js-controller

3.3.22

### Version of Adapter

2.0.6, 2.0.7, 2.10

### Operating system running ioBroker

Raspian Buster

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

[iobroker.2021-12-20.log.txt](https://github.com/klein0r/ioBroker.octoprint/files/7748253/iobroker.2021-12-20.log.txt)

**Comment by OberfragGER** [comment]
Its still in 2.07. , 2.10.
In the meantime i tried 2.0.4
-Its also there. So title is misleading.

**Comment by Ralf-Niemeier** [comment]
Sometimes ! same here.
I can't find no reason or solution 
Adapter Version 2.1.0
thx.

**Comment by klein0r** [comment]
Please test with 2.1.1

If timeout still exceeded:

- Increase timeout in instance config
- Provide debug log

**Comment by Ralf-Niemeier** [comment]
thx

**Comment by OberfragGER** [comment]
Was not working.
I updatet to version 2.20

<html>
<body>
<div class="MuiGrid-root-335 MuiGrid-container-336 MuiGrid-item-337 MuiGrid-align-items-xs-center-344" style="box-sizing: border-box; width: 1724px; display: flex; flex-wrap: wrap; margin: 0px; align-items: center; color: rgba(0, 0, 0, 0.87); font-family: &quot;Segoe UI&quot;, Tahoma, Arial, &quot;Courier New&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="MuiBadge-root-106" title="Fehler anzeigen" style="box-sizing: inherit; display: inline-flex; position: relative; flex-shrink: 0; vertical-align: middle;"><span class="MuiBadge-badge-107 jss5329 jss5330 MuiBadge-anchorOriginTopRightRectangle-112 MuiBadge-colorError-110 MuiBadge-invisible-128" style="box-sizing: border-box; height: 20px; display: flex; padding: 0px 6px; z-index: 1; position: absolute; flex-flow: row wrap; font-size: 0.75rem; min-width: 20px; transition: transform 195ms cubic-bezier(0.4, 0, 0.2, 1) 0ms; align-items: center; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1; place-content: center; border-radius: 10px; color: rgb(255, 255, 255); background-color: rgb(244, 67, 54); top: 10px; right: 10px; transform: scale(0) translate(50%, -50%); transform-origin: 100% 0%;">0</span></span><span class="MuiBadge-root-106" title="Fehler und Warnungen anzeigen" style="box-sizing: inherit; display: inline-flex; position: relative; flex-shrink: 0; vertical-align: middle;"><button class="MuiButtonBase-root-85 MuiIconButton-root-77" tabindex="0" type="button" style="box-sizing: inherit; color: rgba(0, 0, 0, 0.54); border: 0px; cursor: pointer; margin: 0px; display: inline-flex; outline: 0px; padding: 12px; position: relative; align-items: center; user-select: none; border-radius: 50%; vertical-align: middle; justify-content: center; text-decoration: none; background-color: transparent; appearance: none; -webkit-tap-highlight-color: transparent; flex: 0 0 auto; overflow: visible; font-size: 1.5rem; text-align: center; transition: background-color 150ms cubic-bezier(0.4, 0, 0.2, 1) 0ms;"><span class="MuiIconButton-label-84" style="box-sizing: inherit; width: 24px; display: flex; align-items: inherit; justify-content: inherit;"><svg class="MuiSvgIcon-root-86" focusable="false" viewBox="0 0 24 24" aria-hidden="true"><path d="M1 21h22L12 2 1 21zm12-3h-2v-2h2v2zm0-4h-2v-4h2v4z"></path></svg></span><span class="MuiTouchRipple-root-181" style="box-sizing: inherit; inset: 0px; z-index: 0; overflow: hidden; position: absolute; border-radius: inherit; pointer-events: none;"></span></button><span class="MuiBadge-badge-107 jss5329 jss5331 MuiBadge-anchorOriginTopRightRectangle-112" style="box-sizing: border-box; height: 20px; display: flex; padding: 0px 6px; z-index: 1; position: absolute; flex-flow: row wrap; font-size: 0.75rem; min-width: 20px; transition: transform 225ms cubic-bezier(0.4, 0, 0.2, 1) 0ms; align-items: center; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1; place-content: center; border-radius: 10px; top: 10px; right: 10px; transform: scale(1) translate(50%, -50%); transform-origin: 100% 0%; background-color: rgb(255, 193, 7);">4</span></span><div class="jss5318" style="box-sizing: inherit; flex-grow: 1;"></div><div style="box-sizing: inherit;"><button class="MuiButtonBase-root-85 MuiButton-root-136 MuiButton-contained-144 MuiButton-containedPrimary-145" tabindex="0" type="button" style="box-sizing: border-box; color: rgb(255, 255, 255); border: 0px; cursor: pointer; margin: 0px; display: inline-flex; outline: 0px; padding: 6px 16px; position: relative; align-items: center; user-select: none; border-radius: 4px; vertical-align: middle; justify-content: center; text-decoration: none; background-color: rgb(51, 153, 204); appearance: none; -webkit-tap-highlight-color: transparent; font-size: 0.875rem; min-width: 64px; transition: background-color 250ms cubic-bezier(0.4, 0, 0.2, 1) 0ms, box-shadow 250ms cubic-bezier(0.4, 0, 0.2, 1) 0ms, border 250ms cubic-bezier(0.4, 0, 0.2, 1) 0ms; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.75; letter-spacing: 0.02857em; text-transform: uppercase; box-shadow: rgba(0, 0, 0, 0.2) 0px 3px 1px -2px, rgba(0, 0, 0, 0.14) 0px 2px 2px 0px, rgba(0, 0, 0, 0.12) 0px 1px 5px 0px;"><span class="MuiButton-label-137" style="box-sizing: inherit; width: 188.719px; display: inherit; align-items: inherit; justify-content: inherit;"><span class="MuiButton-startIcon-158 MuiButton-iconSizeMedium-161" style="box-sizing: inherit; display: inherit; margin-left: -4px; margin-right: 8px;"><svg class="MuiSvgIcon-root-86" focusable="false" viewBox="0 0 24 24" aria-hidden="true"><path d="M19 12v7H5v-7H3v7c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2v-7h-2zm-6 .67l2.59-2.58L17 11.5l-5 5-5-5 1.41-1.41L11 12.67V3h2z"></path></svg></span>LOG HERUNTERLADEN</span><span class="MuiTouchRipple-root-181" style="box-sizing: inherit; inset: 0px; z-index: 0; overflow: hidden; position: absolute; border-radius: inherit; pointer-events: none;"></span></button></div><div class="jss5318" style="box-sizing: inherit; flex-grow: 1;"></div><p class="MuiTypography-root-234 jss5319 MuiTypography-body2-235" title="Geschätzte Größe" style="box-sizing: inherit; margin: 0px 1rem; font-size: 0.875rem; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 400; line-height: 1.43; letter-spacing: 0.01071em;">Log-Größe:<span> </span><span class="jss5320" style="box-sizing: inherit; font-style: italic;">9.9 MB</span></p></div><div class="MuiGrid-root-335 jss5361 MuiGrid-item-337" style="box-sizing: border-box; margin: 0px; height: 809px; overflow: hidden; color: rgba(0, 0, 0, 0.87); font-family: &quot;Segoe UI&quot;, Tahoma, Arial, &quot;Courier New&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="MuiTableContainer-root-5363 jss5296" style="box-sizing: inherit; width: 1724px; overflow-x: auto; height: 809px;">

Quelle | Zeit | debug | Nachricht
-- | -- | -- | --
octoprint.0 | 2022-01-17 17:06:25.702 | debug | timeout of 2000ms exceeded
octoprint.0 | 2022-01-17 17:06:25.678 | debug | timeout of 2000ms exceeded
octoprint.0 | 2022-01-17 17:06:25.678 | debug | timeout of 2000ms exceeded
octoprint.0 | 2022-01-17 17:06:25.677 | info | error ECONNABORTED from /api/printer: timeout of 2000ms exceeded
octoprint.0 | 2022-01-17 17:06:23.852 | debug | received 200 response from /api/connection with content: {"current":{"baudrate":115200,"port":"/dev/ttyUSB0","printerProfile":"_default","state":"Operational"},"options":{"baudratePreference":0,"baudrates":[250000,230400,115200,57600,38400,19200,9600],"portPreference":"AUTO","ports":["/dev/ttyUSB0"],"printerProfilePreference":"_default","printerProfiles":[{"id":"_default","name":"Ender3V2"}]}}
octoprint.0 | 2022-01-17 17:06:23.701 | debug | sending "get" request to "/plugin/DisplayLayerProgress/values" (http) without data
octoprint.0 | 2022-01-17 17:06:23.675 | debug | sending "get" request to "/api/files?recursive=true" (http) without data
octoprint.0 | 2022-01-17 17:06:23.674 | debug | refreshing file list: started
octoprint.0 | 2022-01-17 17:06:23.674 | debug | refreshing job state: skipped detail refresh (not printing)
octoprint.0 | 2022-01-17 17:06:23.674 | debug | Plugin "Display Layer Progress" is activated - fetching details
octoprint.0 | 2022-01-17 17:06:23.673 | debug | sending "get" request to "/api/system/commands" (http) without data
octoprint.0 | 2022-01-17 17:06:23.671 | debug | sending "get" request to "/api/printer" (http) without data
octoprint.0 | 2022-01-17 17:06:23.670 | debug | sending "get" request to "/api/connection" (http) without data
octoprint.0 | 2022-01-17 17:06:23.670 | debug | connected to OctoPrint API - online! - status: 200
octoprint.0 | 2022-01-17 17:06:23.669 | debug | received 200 response from /api/version with content: {"api":"0.1","server":"1.7.2","text":"OctoPrint 1.7.2"}
octoprint.0 | 2022-01-17 17:06:23.639 | debug | refreshStateTimeout: re-created refresh timeout (API not connected): id 9 - seconds: 10
octoprint.0 | 2022-01-17 17:06:23.637 | debug | sending "get" request to "/api/version" (http) without data
octoprint.0 | 2022-01-17 17:06:23.636 | debug | refreshState: started from "timeout (API not connected)"
octoprint.0 | 2022-01-17 17:06:15.744 | debug | timeout of 2000ms exceeded
octoprint.0 | 2022-01-17 17:06:15.699 | debug | timeout of 2000ms exceeded
octoprint.0 | 2022-01-17 17:06:15.698 | debug | timeout of 2000ms exceeded
octoprint.0 | 2022-01-17 17:06:15.697 | info | error ECONNABORTED from /api/printer: timeout of 2000ms exceeded
octoprint.0 | 2022-01-17 17:06:13.920 | debug | received 200 response from /api/connection with content: {"current":{"baudrate":115200,"port":"/dev/ttyUSB0","printerProfile":"_default","state":"Operational"},"options":{"baudratePreference":0,"baudrates":[250000,230400,115200,57600,38400,19200,9600],"portPreference":"AUTO","ports":["/dev/ttyUSB0"],"printerProfilePreference":"_default","printerProfiles":[{"id":"_default","name":"Ender3V2"}]}}
octoprint.0 | 2022-01-17 17:06:13.741 | debug | sending "get" request to "/plugin/DisplayLayerProgress/values" (http) without data
octoprint.0 | 2022-01-17 17:06:13.689 | debug | sending "get" request to "/api/files?recursive=true" (http) without data
octoprint.0 | 2022-01-17 17:06:13.688 | debug | refreshing file list: started
octoprint.0 | 2022-01-17 17:06:13.688 | debug | refreshing job state: skipped detail refresh (not printing)
octoprint.0 | 2022-01-17 17:06:13.687 | debug | Plugin "Display Layer Progress" is activated - fetching details
octoprint.0 | 2022-01-17 17:06:13.685 | debug | sending "get" request to "/api/system/commands" (http) without data
octoprint.0 | 2022-01-17 17:06:13.683 | debug | sending "get" request to "/api/printer" (http) without data
octoprint.0 | 2022-01-17 17:06:13.682 | debug | sending "get" request to "/api/connection" (http) without data
octoprint.0 | 2022-01-17 17:06:13.682 | debug | connected to OctoPrint API - online! - status: 200
octoprint.0 | 2022-01-17 17:06:13.681 | debug | received 200 response from /api/version with content: {"api":"0.1","server":"1.7.2","text":"OctoPrint 1.7.2"}
octoprint.0 | 2022-01-17 17:06:13.636 | debug | refreshStateTimeout: re-created refresh timeout (API not connected): id 8 - seconds: 10
octoprint.0 | 2022-01-17 17:06:13.635 | debug | sending "get" request to "/api/version" (http) without data
octoprint.0 | 2022-01-17 17:06:13.634 | debug | refreshState: started from "timeout (API not connected)"
octoprint.0 | 2022-01-17 17:06:05.690 | debug | timeout of 2000ms exceeded
octoprint.0 | 2022-01-17 17:06:05.666 | debug | timeout of 2000ms exceeded
octoprint.0 | 2022-01-17 17:06:05.665 | debug | timeout of 2000ms exceeded
octoprint.0 | 2022-01-17 17:06:05.663 | info | error ECONNABORTED from /api/printer: timeout of 2000ms exceeded
octoprint.0 | 2022-01-17 17:06:03.843 | debug | received 200 response from /api/connection with content: {"current":{"baudrate":115200,"port":"/dev/ttyUSB0","printerProfile":"_default","state":"Operational"},"options":{"baudratePreference":0,"baudrates":[250000,230400,115200,57600,38400,19200,9600],"portPreference":"AUTO","ports":["/dev/ttyUSB0"],"printerProfilePreference":"_default","printerProfiles":[{"id":"_default","name":"Ender3V2"}]}}
octoprint.0 | 2022-01-17 17:06:03.688 | debug | sending "get" request to "/plugin/DisplayLayerProgress/values" (http) without data
octoprint.0 | 2022-01-17 17:06:03.656 | debug | sending "get" request to "/api/files?recursive=true" (http) without data
octoprint.0 | 2022-01-17 17:06:03.656 | debug | refreshing file list: started
octoprint.0 | 2022-01-17 17:06:03.656 | debug | refreshing job state: skipped detail refresh (not printing)
octoprint.0 | 2022-01-17 17:06:03.655 | debug | Plugin "Display Layer Progress" is activated - fetching details
octoprint.0 | 2022-01-17 17:06:03.654 | debug | sending "get" request to "/api/system/commands" (http) without data
octoprint.0 | 2022-01-17 17:06:03.653 | debug | sending "get" request to "/api/printer" (http) without data
octoprint.0 | 2022-01-17 17:06:03.652 | debug | sending "get" request to "/api/connection" (http) without data
octoprint.0 | 2022-01-17 17:06:03.652 | debug | connected to OctoPrint API - online! - status: 200
octoprint.0 | 2022-01-17 17:06:03.651 | debug | received 200 response from /api/version with content: {"api":"0.1","server":"1.7.2","text":"OctoPrint 1.7.2"}
octoprint.0 | 2022-01-17 17:06:03.625 | debug | refreshStateTimeout: re-created refresh timeout (API not connected): id 7 - seconds: 10
octoprint.0 | 2022-01-17 17:06:03.624 | debug | sending "get" request to "/api/version" (http) without data
octoprint.0 | 2022-01-17 17:06:03.623 | debug | refreshState: started from "timeout (API not connected)"
octoprint.0 | 2022-01-17 17:05:55.791 | debug | received 200 response from /plugin/DisplayLayerProgress/values with content: {"currentFilename":"","fanSpeed":"-","feedrate":"-","feedrateG0":"-","feedrateG1":"-","height":{"current":"-","currentFormatted":"-","total":"-","totalFormatted":"-"},"layer":{"averageLayerDuration":"-","averageLayerDurationInSeconds":"-","current":"-","lastLayerDuration":"-","lastLayerDurationInSeconds":"-","total":"-"},"print":{"changeFilamentCount":0,"changeFilamentTimeLeft":"-","changeFilamentTimeLeftInSeconds":0,"estimatedChangedFilamentTime":"-","estimatedEndTime":"-","m73progress":"","printerState":"operational","progress":"0","timeLeft":"-","timeLeftInSeconds":"-"}}
octoprint.0 | 2022-01-17 17:05:55.666 | debug | timeout of 2000ms exceeded
octoprint.0 | 2022-01-17 17:05:55.665 | info | error ECONNABORTED from /api/system/commands: timeout of 2000ms exceeded
octoprint.0 | 2022-01-17 17:05:54.579 | debug | sending "get" request to "/plugin/DisplayLayerProgress/values" (http) without data
octoprint.0 | 2022-01-17 17:05:53.866 | debug | received 200 response from /api/printer with content: {"sd":{"ready":true},"state":{"error":"","flags":{"cancelling":false,"closedOrError":false,"error":false,"finishing":false,"operational":true,"paused":false,"pausing":false,"printing":false,"ready":true,"resuming":false,"sdReady":true},"text":"Operational"},"temperature":{"bed":{"actual":20.39,"offset":0,"target":0},"tool0":{"actual":20.64,"offset":0,"target":0}}}
octoprint.0 | 2022-01-17 17:05:53.847 | debug | received 200 response from /api/connection with content: {"current":{"baudrate":115200,"port":"/dev/ttyUSB0","printerProfile":"_default","state":"Operational"},"options":{"baudratePreference":0,"baudrates":[250000,230400,115200,57600,38400,19200,9600],"portPreference":"AUTO","ports":["/dev/ttyUSB0"],"printerProfilePreference":"_default","printerProfiles":[{"id":"_default","name":"Ender3V2"}]}}
octoprint.0 | 2022-01-17 17:05:53.658 | debug | sending "get" request to "/api/files?recursive=true" (http) without data
octoprint.0 | 2022-01-17 17:05:53.658 | debug | refreshing file list: started
octoprint.0 | 2022-01-17 17:05:53.654 | debug | refreshing job state: skipped detail refresh (not printing)
octoprint.0 | 2022-01-17 17:05:53.653 | debug | Plugin "Display Layer Progress" is activated - fetching details
octoprint.0 | 2022-01-17 17:05:53.652 | debug | sending "get" request to "/api/system/commands" (http) without data
octoprint.0 | 2022-01-17 17:05:53.651 | debug | sending "get" request to "/api/printer" (http) without data
octoprint.0 | 2022-01-17 17:05:53.650 | debug | sending "get" request to "/api/connection" (http) without data
octoprint.0 | 2022-01-17 17:05:53.649 | debug | connected to OctoPrint API - online! - status: 200
octoprint.0 | 2022-01-17 17:05:53.649 | debug | received 200 response from /api/version with content: {"api":"0.1","server":"1.7.2","text":"OctoPrint 1.7.2"}
octoprint.0 | 2022-01-17 17:05:53.623 | debug | refreshStateTimeout: re-created refresh timeout (API not connected): id 6 - seconds: 10
octoprint.0 | 2022-01-17 17:05:53.622 | debug | sending "get" request to "/api/version" (http) without data
octoprint.0 | 2022-01-17 17:05:53.621 | debug | refreshState: started from "timeout (API not connected)"
octoprint.0 | 2022-01-17 17:05:45.691 | debug | timeout of 2000ms exceeded
octoprint.0 | 2022-01-17 17:05:45.661 | debug | timeout of 2000ms exceeded
octoprint.0 | 2022-01-17 17:05:45.660 | debug | timeout of 2000ms exceeded
octoprint.0 | 2022-01-17 17:05:45.659 | info | error ECONNABORTED from /api/printer: timeout of 2000ms exceeded
octoprint.0 | 2022-01-17 17:05:43.842 | debug | received 200 response from /api/connection with content: {"current":{"baudrate":115200,"port":"/dev/ttyUSB0","printerProfile":"_default","state":"Operational"},"options":{"baudratePreference":0,"baudrates":[250000,230400,115200,57600,38400,19200,9600],"portPreference":"AUTO","ports":["/dev/ttyUSB0"],"printerProfilePreference":"_default","printerProfiles":[{"id":"_default","name":"Ender3V2"}]}}
octoprint.0 | 2022-01-17 17:05:43.688 | debug | sending "get" request to "/plugin/DisplayLayerProgress/values" (http) without data
octoprint.0 | 2022-01-17 17:05:43.656 | debug | sending "get" request to "/api/files?recursive=true" (http) without data
octoprint.0 | 2022-01-17 17:05:43.656 | debug | refreshing file list: started
octoprint.0 | 2022-01-17 17:05:43.656 | debug | refreshing job state: skipped detail refresh (not printing)
octoprint.0 | 2022-01-17 17:05:43.655 | debug | Plugin "Display Layer Progress" is activated - fetching details
octoprint.0 | 2022-01-17 17:05:43.654 | debug | sending "get" request to "/api/system/commands" (http) without data
octoprint.0 | 2022-01-17 17:05:43.651 | debug | sending "get" request to "/api/printer" (http) without data
octoprint.0 | 2022-01-17 17:05:43.650 | debug | sending "get" request to "/api/connection" (http) without data
octoprint.0 | 2022-01-17 17:05:43.650 | debug | connected to OctoPrint API - online! - status: 200
octoprint.0 | 2022-01-17 17:05:43.649 | debug | received 200 response from /api/version with content: {"api":"0.1","server":"1.7.2","text":"OctoPrint 1.7.2"}
octoprint.0 | 2022-01-17 17:05:43.622 | debug | refreshStateTimeout: re-created refresh timeout (API not connected): id 5 - seconds: 10
octoprint.0 | 2022-01-17 17:05:43.620 | debug | sending "get" request to "/api/version" (http) without data
octoprint.0 | 2022-01-17 17:05:43.620 | debug | refreshState: started from "timeout (API not connected)"
octoprint.0 | 2022-01-17 17:05:35.712 | debug | timeout of 2000ms exceeded
octoprint.0 | 2022-01-17 17:05:35.658 | debug | timeout of 2000ms exceeded
octoprint.0 | 2022-01-17 17:05:35.657 | debug | timeout of 2000ms exceeded
octoprint.0 | 2022-01-17 17:05:35.656 | info | error ECONNABORTED from /api/printer: timeout of 2000ms exceeded
octoprint.0 | 2022-01-17 17:05:33.845 | debug | received 200 response from /api/connection with content: {"current":{"baudrate":115200,"port":"/dev/ttyUSB0","printerProfile":"_default","state":"Operational"},"options":{"baudratePreference":0,"baudrates":[250000,230400,115200,57600,38400,19200,9600],"portPreference":"AUTO","ports":["/dev/ttyUSB0"],"printerProfilePreference":"_default","printerProfiles":[{"id":"_default","name":"Ender3V2"}]}}
octoprint.0 | 2022-01-17 17:05:33.709 | debug | sending "get" request to "/plugin/DisplayLayerProgress/values" (http) without data
octoprint.0 | 2022-01-17 17:05:33.653 | debug | sending "get" request to "/api/files?recursive=true" (http) without data
octoprint.0 | 2022-01-17 17:05:33.653 | debug | refreshing file list: started
octoprint.0 | 2022-01-17 17:05:33.653 | debug | refreshing job state: skipped detail refresh (not printing)
octoprint.0 | 2022-01-17 17:05:33.652 | debug | Plugin "Display Layer Progress" is activated - fetching details
octoprint.0 | 2022-01-17 17:05:33.651 | debug | sending "get" request to "/api/system/commands" (http) without data
octoprint.0 | 2022-01-17 17:05:33.650 | debug | sending "get" request to "/api/printer" (http) without data
octoprint.0 | 2022-01-17 17:05:33.648 | debug | sending "get" request to "/api/connection" (http) without data
octoprint.0 | 2022-01-17 17:05:33.648 | debug | connected to OctoPrint API - online! - status: 200
octoprint.0 | 2022-01-17 17:05:33.647 | debug | received 200 response from /api/version with content: {"api":"0.1","server":"1.7.2","text":"OctoPrint 1.7.2"}
octoprint.0 | 2022-01-17 17:05:33.619 | debug | refreshStateTimeout: re-created refresh timeout (API not connected): id 4 - seconds: 10
octoprint.0 | 2022-01-17 17:05:33.616 | debug | sending "get" request to "/api/version" (http) without data
octoprint.0 | 2022-01-17 17:05:33.615 | debug | refreshState: started from "timeout (API not connected)"
smartmeter.0 | 2022-01-17 17:05:27.094 | info | Received 7 values, 3 updated
octoprint.0 | 2022-01-17 17:05:25.719 | debug | timeout of 2000ms exceeded
octoprint.0 | 2022-01-17 17:05:25.657 | debug | timeout of 2000ms exceeded
octoprint.0 | 2022-01-17 17:05:25.656 | info | error ECONNABORTED from /api/system/commands: timeout of 2000ms exceeded
octoprint.0 | 2022-01-17 17:05:23.910 | debug | received 200 response from /api/printer with content: {"sd":{"ready":true},"state":{"error":"","flags":{"cancelling":false,"closedOrError":false,"error":false,"finishing":false,"operational":true,"paused":false,"pausing":false,"printing":false,"ready":true,"resuming":false,"sdReady":true},"text":"Operational"},"temperature":{"bed":{"actual":20.35,"offset":0,"target":0},"tool0":{"actual":20.59,"offset":0,"target":0}}}
octoprint.0 | 2022-01-17 17:05:23.885 | debug | received 200 response from /api/connection with content: {"current":{"baudrate":115200,"port":"/dev/ttyUSB0","printerProfile":"_default","state":"Operational"},"options":{"baudratePreference":0,"baudrates":[250000,230400,115200,57600,38400,19200,9600],"portPreference":"AUTO","ports":["/dev/ttyUSB0"],"printerProfilePreference":"_default","printerProfiles":[{"id":"_default","name":"Ender3V2"}]}}
octoprint.0 | 2022-01-17 17:05:23.716 | debug | sending "get" request to "/plugin/DisplayLayerProgress/values" (http) without data
octoprint.0 | 2022-01-17 17:05:23.653 | debug | sending "get" request to "/api/files?recursive=true" (http) without data
octoprint.0 | 2022-01-17 17:05:23.653 | debug | refreshing file list: started
octoprint.0 | 2022-01-17 17:05:23.652 | debug | refreshing job state: skipped detail refresh (not printing)
octoprint.0 | 2022-01-17 17:05:23.652 | debug | Plugin "Display Layer Progress" is activated - fetching details
octoprint.0 | 2022-01-17 17:05:23.651 | debug | sending "get" request to "/api/system/commands" (http) without data
octoprint.0 | 2022-01-17 17:05:23.649 | debug | sending "get" request to "/api/printer" (http) without data
octoprint.0 | 2022-01-17 17:05:23.648 | debug | sending "get" request to "/api/connection" (http) without data
octoprint.0 | 2022-01-17 17:05:23.648 | debug | connected to OctoPrint API - online! - status: 200
octoprint.0 | 2022-01-17 17:05:23.647 | debug | received 200 response from /api/version with content: {"api":"0.1","server":"1.7.2","text":"OctoPrint 1.7.2"}
octoprint.0 | 2022-01-17 17:05:23.615 | debug | refreshStateTimeout: re-created refresh timeout (API not connected): id 3 - seconds: 10
octoprint.0 | 2022-01-17 17:05:23.613 | debug | sending "get" request to "/api/version" (http) without data
octoprint.0 | 2022-01-17 17:05:23.613 | debug | refreshState: started from "timeout (API not connected)"
octoprint.0 | 2022-01-17 17:05:15.776 | debug | received 200 response from /plugin/DisplayLayerProgress/values with content: {"currentFilename":"","fanSpeed":"-","feedrate":"-","feedrateG0":"-","feedrateG1":"-","height":{"current":"-","currentFormatted":"-","total":"-","totalFormatted":"-"},"layer":{"averageLayerDuration":"-","averageLayerDurationInSeconds":"-","current":"-","lastLayerDuration":"-","lastLayerDurationInSeconds":"-","total":"-"},"print":{"changeFilamentCount":0,"changeFilamentTimeLeft":"-","changeFilamentTimeLeftInSeconds":0,"estimatedChangedFilamentTime":"-","estimatedEndTime":"-","m73progress":"","printerState":"operational","progress":"0","timeLeft":"-","timeLeftInSeconds":"-"}}
octoprint.0 | 2022-01-17 17:05:15.664 | debug | timeout of 2000ms exceeded
octoprint.0 | 2022-01-17 17:05:15.663 | debug | timeout of 2000ms exceeded
octoprint.0 | 2022-01-17 17:05:15.661 | info | error ECONNABORTED from /api/printer: timeout of 2000ms exceeded
octoprint.0 | 2022-01-17 17:05:14.042 | debug | sending "get" request to "/plugin/DisplayLayerProgress/values" (http) without data
octoprint.0 | 2022-01-17 17:05:13.845 | debug | received 200 response from /api/connection with content: {"current":{"baudrate":115200,"port":"/dev/ttyUSB0","printerProfile":"_default","state":"Operational"},"options":{"baudratePreference":0,"baudrates":[250000,230400,115200,57600,38400,19200,9600],"portPreference":"AUTO","ports":["/dev/ttyUSB0"],"printerProfilePreference":"_default","printerProfiles":[{"id":"_default","name":"Ender3V2"}]}}
octoprint.0 | 2022-01-17 17:05:13.657 | debug | sending "get" request to "/api/files?recursive=true" (http) without data
octoprint.0 | 2022-01-17 17:05:13.656 | debug | refreshing file list: started
octoprint.0 | 2022-01-17 17:05:13.655 | debug | refreshing job state: skipped detail refresh (not printing)
octoprint.0 | 2022-01-17 17:05:13.654 | debug | Plugin "Display Layer Progress" is activated - fetching details
octoprint.0 | 2022-01-17 17:05:13.653 | debug | sending "get" request to "/api/system/commands" (http) without data
octoprint.0 | 2022-01-17 17:05:13.651 | debug | sending "get" request to "/api/printer" (http) without data
octoprint.0 | 2022-01-17 17:05:13.648 | debug | sending "get" request to "/api/connection" (http) without data
octoprint.0 | 2022-01-17 17:05:13.647 | debug | connected to OctoPrint API - online! - status: 200
octoprint.0 | 2022-01-17 17:05:13.646 | debug | received 200 response from /api/version with content: {"api":"0.1","server":"1.7.2","text":"OctoPrint 1.7.2"}
octoprint.0 | 2022-01-17 17:05:13.613 | debug | refreshStateTimeout: re-created refresh timeout (API not connected): id 2 - seconds: 10
octoprint.0 | 2022-01-17 17:05:13.593 | debug | sending "get" request to "/api/version" (http) without data
octoprint.0 | 2022-01-17 17:05:13.592 | debug | refreshState: started from "onReady"
octoprint.0 | 2022-01-17 17:05:13.503 | info | starting. Version 2.2.0 in /opt/iobroker/node_modules/iobroker.octoprint, node: v14.18.2, js-controller: 3.3.22
octoprint.0 | 2022-01-17 17:05:13.324 | debug | Plugin sentry Initialize Plugin (enabled=true)
octoprint.0 | 2022-01-17 17:05:12.732 | debug | statesDB connected
octoprint.0 | 2022-01-17 17:05:12.731 | debug | States connected to redis: 127.0.0.1:9000
octoprint.0 | 2022-01-17 17:05:12.676 | debug | States create User PubSub Client
octoprint.0 | 2022-01-17 17:05:12.675 | debug | States create System PubSub Client
octoprint.0 | 2022-01-17 17:05:12.664 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
octoprint.0 | 2022-01-17 17:05:12.663 | debug | objectDB connected
octoprint.0 | 2022-01-17 17:05:12.656 | debug | Objects connected to redis: 127.0.0.1:9001
octoprint.0 | 2022-01-17 17:05:12.622 | debug | Objects client initialize lua scripts
octoprint.0 | 2022-01-17 17:05:12.621 | debug | Objects create User PubSub Client
octoprint.0 | 2022-01-17 17:05:12.620 | debug | Objects create System PubSub Client
octoprint.0 | 2022-01-17 17:05:12.618 | debug | Objects client ready ... initialize now
octoprint.0 | 2022-01-17 17:05:12.576 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001

</div></div>
</body>
</html>

**Comment by klein0r** [comment]
@OberfragGER Ist dein System stark ausgelastet? 2 Sekunden ist ja eigentlich schon sehr lange für den Request. Sonst stell den Timeout doch einfach mal höher in der Config. Zumal es auch immer andere Ressourcen sind die in Timeouts laufen.
