### ISSUE TITLE
Zeit für Druckjob

### ISSUE THREAD

**Issue by Negalein** [klein0r/ioBroker.octoprint#67]
Es gibt derzeit `octoprint.0.printjob.progress.printtime` (verstrichene Zeit) und `octoprint.0.printjob.progress.printtime_left` (Restzeit).

Cool wäre noch die Gesamtzeit für den Druckjob.
In Octoprint wird sie angezeigt.

Danke

PS: wo ist deine Kaffeekassa? :)

**Comment by joergeli** [comment]
@Negalein 
Falls du Interesse hast und dich ein weinig mit JavaScript auskennst:

Ich habe mir in ioBroker mit JS aus "verstrichene Zeit" und "Restzeit" einen Datenpunkt gebastelt, wann der Drucker fertig hat ;-)

![mini-octo](https://user-images.githubusercontent.com/62521927/150267394-54591ce6-58d3-4d1d-bf9a-3ccc5442967c.jpg)

Also **um wieviel Uhr** (= Fertigstellung) der Druckjob fertig ist.
(Datum ist mit drin, weil der Druckjob ja auch bis zum nächsten Tag laufen könnte.)

Gesamtzeit könnte ich auch noch stricken.

Kann das Script bei Bedarf gerne im ioBroker-Forum einstellen.

Gruß
Jörg

**Comment by Negalein** [comment]
> Gesamtzeit könnte ich auch noch stricken.
> 
> Kann das Script bei Bedarf gerne im ioBroker-Forum einstellen.

Hi Jörg!

Danke, das wäre toll.
Somit könnte @klein0r sich das im Adapter ersparen.
