### ISSUE TITLE
keine DP mehr in octoprint.0.files für thumbnail, thumbnail_url

### ISSUE THREAD

**Issue by sjfm-design** [klein0r/ioBroker.octoprint#69]
### The problem

gestern aufgefallen beim slicen. seit 3.0.0 werden bei mir keine der genannten DP mehr erzeugt.
in octoprint werden die thumbs aber angezeigt.
am 20. jänner hat das noch funktioniert, wie ich in meinen octoprint.0.files sehen kann.

### Version of nodejs

14.18.2

### Version of ioBroker js-controller

3.3.22

### Version of Adapter

3.0.0

### Operating system running ioBroker

Linux octopi 5.10.63-v7

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by sjfm-design** [comment]
nach 2 tagen fehler gefunden! in den einstllungen wurden meine plugin einstellungen beim update geändert!
![grafik](https://user-images.githubusercontent.com/30467409/152011074-c84c4347-8e00-44d1-85a5-d26f03fad496.png)
jetzt wieder die einstllungen, wie vor dem update...

**Comment by klein0r** [comment]
Also alles behoben? Ich mach hier mal zu 😄
