### ISSUE TITLE
this.setForeignBinaryState is not a function

### ISSUE THREAD

**Issue by Negalein** [klein0r/ioBroker.octoprint#75]
### The problem

bekomme haufenweise dieser Meldungen im Log.

`this.setForeignBinaryState is not a function`

### Version of nodejs

14.19.1

### Version of ioBroker js-controller

3.3.22

### Version of Adapter

3.2.1

### Operating system running ioBroker

Ubuntu

**Comment by klein0r** [comment]
Habe vergessen die js-controller dependency hoch zu stellen 😭
Mindestens 4.0.15 nötig

**Comment by Negalein** [comment]
> Habe vergessen die js-controller dependency hoch zu stellen 😭 Mindestens 4.0.15 nötig

Danke, hab gleich auf 4.0.23 upgedatet! :)

**Comment by Negalein** [comment]
seit JS-Controller 4.0.23 keine Probleme!

**Comment by klein0r** [comment]
Ja ich muss noch die dependency erhöhen damit sonst niemand in die Falle läuft

**Comment by klein0r** [comment]
Fixed in 3.2.2
