### ISSUE TITLE
Prusa Slicer Thumbnails - Download error

### ISSUE THREAD

**Issue by Negalein** [klein0r/ioBroker.octoprint#76]
### The problem

bekomme haufenweise dieser Meldungen.

Octoprint läuft, Drucker ist aus.

`received 400 response from plugin/prusaslicerthumbnails/thumbnail/Mario/Bilskirnir_body_groß.png?20220506175305`
`received 400 response from plugin/prusaslicerthumbnails/thumbnail/Mario/Bilskirnir_rear_groß.png?20220506175609`
`received 400 response from plugin/prusaslicerthumbnails/thumbnail/Mario/Bilskirnir_front_groß.png?20220506175505`

Diese 3 Files wurden vor kurzem hochgeladen.

### Version of nodejs

14.19.1

### Version of ioBroker js-controller

4.0.23

### Version of Adapter

3.2.2

### Operating system running ioBroker

Ubuntu

**Comment by klein0r** [comment]
Ich habe mit einer neuen Version angefangen, in welcher sich vieles für die Plugins geändert hat. Noch etwas Geduld bitte.

**Comment by Negalein** [comment]
> Ich habe mit einer neuen Version angefangen, in welcher sich vieles für die Plugins geändert hat. Noch etwas Geduld bitte.

Danke

**Comment by klein0r** [comment]
Please test with 4.0.0
